version: '3.6'
services:
  mongodb:
    container_name: mongodb
    image: mongo:7.0.9
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
    ports:
      - 27017:27017
    networks:
      - mongodb-net
  mongo-express:  
    container_name: mongo-express
    image: mongo-express
    environment:
        - ME_CONFIG_MONGODB_SERVER=mongodb
        - ME_CONFIG_MONGODB_PORT=27017
    networks:
      - mongodb-net
    ports:
      - 8888:8081
    depends_on:
      - mongodb
networks: 
    mongodb-net:
      driver: bridge
volumes:
  mongodb-data:
  mongodb-config:
