version: '3.6'
services:
  mongodb:
    container_name: mongodb
    image: mongo:3.6
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb 
    ports:
      - 27017:27017
    networks:
      - mongodb-network
  mongo-express:  
    container_name: mongo-express
    image: mongo-express
    environment:
        - ME_CONFIG_MONGODB_SERVER=mongodb
        - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
        - mongodb
    networks:
      - mongodb-network
    ports:
      - 8888:8081
    depends_on:
      - mongodb
networks: 
    mongodb-network:
      driver: bridge
volumes:
  db-data:
  mongo-config:
