services:
  redis:
    image: redis:8.0-M04-alpine
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    hostname: redisinsight
    environment:
      - RI_REDIS_HOST=redis
    ports:
      - 5540:5540
    volumes:
      - redis-insight-data:/data
    depends_on:
      - redis
volumes:
  redis-data:
  redis-insight-data: